### ISSUE TITLE
Using <br/>  within   <p>

### ISSUE THREAD

**Issue by MikeLesaa** [PHPOffice/PHPWord#1370]
Hi!
When  I use tab `<br/>` in html without other tags - it's ok. But if it is wrapped  by p, in result br 
is not replaced by line break in docx file.

```php
       require __DIR__ . '/vendor/autoload.php';

        $html .= '<p>line1<br/>lin2</p>';

        $phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection();

        \PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($fileName);
```

### Context

* PHP version: 5.4
* PHPWord version: 0.14

Q: https://stackoverflow.com/questions/50409428/using-br-within-p

**Comment by troosan** [comment]
this was already fixed by #1277

**Comment by MikeLesaa** [comment]
@troosan I tried to use dev-develop version by composer but it does not work too. I saw that you change src/PhpWord/Reader/Word2007/AbstractPart.php file. But I tried read not doc-file, I tried to read html-file - I have error while converting from html to .docx file

**Comment by oleyur** [comment]
@troosan It was not fixed!!
<br> in <p> is not parsing now while we try read html and convert it to docx
